site_name: Unburden Your Home Directory
pages:
  - [index.md, Project Home]
  - [installation.md, Installation and Dependencies]
  - [howto.md, Getting Started]
  - [configuration.md, Configuration]
  - [troubleshooting.md, Troubleshooting]
  - [source-code.md, Source Code]
  - [license.md, "License, Copyright and Author"]
  - [contact.md, Contact and Community]
  - [bugs.md, Bugs]
  - [qa.md, Quality Assurance]
  - [see-also.md, See Also]
